SELECT
?form ?formLabel
(GROUP_CONCAT(DISTINCT ?featureLabel; separator="|") AS ?features)
WHERE {
wd:%s ontolex:lexicalForm ?form .
?form ontolex:representation ?formLabel .
OPTIONAL {
?form wikibase:grammaticalFeature ?feature .
?feature rdfs:label ?featureLabel .
FILTER (LANG(?featureLabel) = "en")
}
OPTIONAL {
?form wdt:P5279 ?hyphenation
}
}
GROUP BY ?form ?formLabel
ORDER BY (STR(?form))